name: Update GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}  # ✅ ĐÚNG CÁCH
          base: header, activity, community, repositories
          plugin_languages: yes
          plugin_followup: yes
          plugin_habits: no
          plugin_lines: yes
          plugin_reactions: yes
          plugin_repositories: yes
