name: Update GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *"  # Chạy mỗi ngày lúc 00:00 UTC
  workflow_dispatch:  # Cho phép chạy thủ công

jobs:
  update-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{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}}
          base: header, activity, community, repositories
          plugin_languages: yes
          plugin_followup: yes
          plugin_habits: no
          plugin_lines: yes
          plugin_reactions: yes
          plugin_repositories: yes
